pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./--addressing------------------.html","5. Architecture &#38; Internals &#62; 5.2 Memory, Addressing &#38; Deep Dives &#62; Addressing","Virtual-to-physical translation is performed by Ev6Translator (mmuLib) exactly as the EV6 architecture specifies. In PAL mode the address bypasses...",""],
["./--addressing--tlb.html","5. Architecture &#38; Internals &#62; 5.2 Memory, Addressing &#38; Deep Dives &#62; Addressing &#38; TLB","This appendix is the implementation-level companion to the Addressing page. It walks the V6 translation path from a virtual address to a physical ...",""],
["./--appendix---ds10.html","8. Appendices - Developer Reference &#62; 8.1 Platform Appendices &#62; Appendix - DS10","Reference material specific to the DS10 platform -- EmulatR&#39;s reference model, driven end to end to the SRM prompt (DS20 also boots to the prompt;...",""],
["./--appendix-ds20-_-es40-_-es45.html","8. Appendices - Developer Reference &#62; 8.1 Platform Appendices &#62; Appendix DS20 / ES40 / ES45","The larger multi-CPU machines. DS20 is modeled and boots to the SRM &#62;&#62;&#62; prompt; ES40 is in active bring-up (Typhoon variant + Ali M1543C ...",""],
["./--atapi-devices.html","4. Operating EmulatR &#62; 4.4 Storage &#62; ATAPI Devices","The CD-ROM is presented as an ATAPI device on the IDE channel -- dqa0.0.0.105.0, \"EMULATR VIRTUAL CDROM\". ATAPI / IDE scaffolding for th...",""],
["./--automatic-_-creating-_-resto.html","4. Operating EmulatR &#62; 4.5 Snapshots &#38; Boot Acceleration","Automatic snapshots Periodic auto_*.axpsnap saves are on by default. Disable them for clean cold-boot / profiling runs:  --autosnapshot off #...",""],
["./--boot-acceleration-entry-snap.html","4. Operating EmulatR &#62; 4.5 Snapshots &#38; Boot Acceleration &#62; Boot Acceleration - Entry Snapshot","NOT IMPLEMENTED IN THIS BUILD. The EMULATR_FAST_DECOMPRESS lever described below is not present: nothing in the emulator reads that name, and no e...",""],
["./--building-from-source.html","2. Installation &#62; Building from Source","EmulatR is a CMake project built with MSVC (C++20). The build tree produces Emulatr.exe under out/build/&#60;tree&#62;-&#60;config&#62;/run/, with the...",""],
["./--clean-shutdown.html","3. Quick Start &#62; Clean Shutdown","There are two graceful paths and one hard kill.  1. Stop sentinel (flushes NVRAM via ~Machine) From the run directory, in PowerShell:  i...",""],
["./--cmake-macro-guards----------.html","5. Architecture &#38; Internals &#62; 5.1 Execution, Decode &#38; Internals &#62; CMake Macro Guards","A number of EmulatR behaviors are selected at build time through CMake options that define compile-guard macros, rather than at run time. This kee...",""],
["./--common-commands.html","4. Operating EmulatR &#62; 4.3 SRM Console &#62; Common Commands","The commands used most often at the &#62;&#62;&#62; prompt. Each show command has its own page in this subsection.",""],
["./--configuring----------(moved-.html","4. Operating EmulatR &#62; 4.1 Configuring &#38; Running &#62; Configuring","Configuration precedence (lowest to highest): compiled-in struct defaults &#60; Emulatr.ini &#60; command-line qualifiers. The committed ini drives ...",""],
["./--configuring-a-system-with-t.html","4. Operating EmulatR &#62; 4.1 Configuring &#38; Running &#62; Configuring a System with the Launcher","This topic walks through configuring an emulated machine from a fresh installation to a booted guest. Work through the steps in order; each one bu...",""],
["./--connecting-to-the-console.html","3. Quick Start &#62; Connecting to the Console","The emulator exposes a RAW TCP console (default localhost:10023). Unless EMULATR_NO_PUTTY is set, PuTTY is launched for you. To attach a client ma...",""],
["./--console-connection-issues---.html","7. Troubleshooting &#62; Console Connection Issues","For refused, timed-out, or silent console connections, the full client coverage is in the Terminal Clients page. In brief, check three things:",""],
["./--console-support------(moved-.html","4. Operating EmulatR &#62; 4.2 Console Connectivity &#62; Console Support","EmulatR exposes its console as a RAW TCP stream (default localhost:10023) -- there is no Telnet option negotiation, so a raw-capable client is pre...",""],
["./--create-guest-disk-storage---.html","4. Operating EmulatR &#62; 4.4 Storage &#62; Create Guest Disk Storage","EmulatR provisions disk images two ways: automatically at boot, driven by the platform manifest (create_if_missing), and manually with the tools/m...",""],
["./--current-development-status--.html","1. Introduction &#62; Current Development Status","This page is a plain-language snapshot of where EmulatR stands as of August 2026 -- what works end to end, the milestone the project is working to...",""],
["./--current-platform-support.html","1. Introduction &#62; Current Platform Support","A platform manifest describes the machine&#39;s device tree. It is named after the FIRMWARE IMAGE that actually loaded, not after the model name: firm...",""],
["./--dependencies----------------.html","2. Installation &#62; Dependencies","What EmulatR is built with and what it relies on at build and run time. Versions are those the project currently builds against.",""],
["./--development-conventions.html","6. Reference &#62; Development Conventions","The standing conventions for working in the EmulatR tree. The file-placement rules are also encoded as Cowork skills so an assistant follows them ...",""],
["./--diagnostics--debugging---(ne.html","4. Operating EmulatR &#62; 4.8 Logging &#38; Diagnostics &#62; Diagnostics &#38; Debugging","Diagnostics are turned on with runtime EMULATR_* environment variables, set in the launching shell before the process starts. The complete table l...",""],
["./--dispatchtables.html","5. Architecture &#38; Internals &#62; 5.1 Execution, Decode &#38; Internals &#62; DispatchTables","The dispatch tables are how the Decode stage turns a raw instruction word into a grain leaf. They are generated into DispatchTables.cpp from the m...",""],
["./--emulatr-will-not-start.html","7. Troubleshooting &#62; EmulatR will not start","Console port already in use. Check with netstat -ano &#124; findstr 10023 and free it, or set EMULATR_CONSOLE_PORT.",""],
["./--env-vars-operation-ref-_-kil.html","8. Appendices - Developer Reference &#62; 8.1 Platform Appendices &#62; Appendix - DS10 &#62; Env Vars, Shutdown &#38; Known Limitations","The DS10 operational quick reference: where the environment-variable controls live, how to stop a running instance cleanly, and the limitations a ...",""],
["./--environment-variables-(emula.html","6. Reference &#62; Environment Variables (EMULATR_*)","The runtime environment variables EmulatR reads at launch, plus the compile-time flags that look like env vars but are CMake options. All values a...",""],
["./--es40-tig-module-reset.html","5. Architecture &#38; Internals &#62; 5.5 PALcode, HWRPB &#38; SMP &#62; ES40 TIG Module Reset (Experimental)","On the ES40 in silicon mode, exiting the firmware update utility (or an update srm followed by the console restart) can stall at Initializing.... ...",""],
["./--evaluate-address.html","4. Operating EmulatR &#62; 4.3 SRM Console &#62; &#62;&#62;&#62; Evaluate Address","At the &#62;&#62;&#62; prompt the SRM console can read and write memory directly -- useful for inspecting device CSRs and firmware state during debug...",""],
["./--example-(console)-execution.html","7. Troubleshooting &#62; Example (Console) execution","A console debugging session on a current build (1024 MB, DS10 268 MHz). Note the cosmetic \"ISA table corrupt\" message at power-up (the f...",""],
["./--example---performance.html","4. Operating EmulatR &#62; 4.1 Configuring &#38; Running &#62; Example - Performance","A representative cold-boot transcript, captured on an earlier build - the banner below reads V1.4 where a current run shows the X1.6-15 badge form...",""],
["./--executing------------(moved).html","4. Operating EmulatR &#62; 4.1 Configuring &#38; Running &#62; Executing","Beyond the basic launch (see Launching EmulatR), a few run scenarios come up often. All are launched from the Emulatr root and write diagnostics t...",""],
["./--executing-two-instances.html","4. Operating EmulatR &#62; 4.1 Configuring &#38; Running &#62; Executing Two Instances","Two instances launched from the same directory share ds10_v7_3.rom and the snapshots/ directory, and concurrent NVRAM writes can corrupt the flash...",""],
["./--execution-flight-plan-------.html","5. Architecture &#38; Internals &#62; 5.1 Execution, Decode &#38; Internals &#62; Execution Flight Plan","A cold boot is a fixed sequence of stages from reset to the interactive prompt. Each instruction along the way is carried through the six in-order...",""],
["./--execution-_-boot-internals.html","5. Architecture &#38; Internals &#62; 5.1 Execution, Decode &#38; Internals &#62; Execution / Boot Internals","This appendix is the implementation-level companion to the Execution Flight Plan. It walks one instruction through V6&#39;s six pipeline stages, then ...",""],
["./--feature-matrix.html","1. Introduction &#62; Feature Matrix","Subsystem status as of August 2026. This reflects the DS10 / DS20 target, with ES40 in active bring-up; status evolves and should be reconfirmed a...",""],
["./--firmware-decode--decompressi.html","5. Architecture &#38; Internals &#62; 5.4 Firmware Decode &#38; Decompression","The shipped SRM image is compressed. At every cold boot the firmware decompresses itself on the emulated CPU, using the original DEC SRM decompres...",""],
["./--firmware-hangs-_-slow-boot-_.html","7. Troubleshooting &#62; Firmware Hangs / Slow Boot / Missing Devices","Firmware hangs (usually timed loops, not crashes) Some long pauses are time-based firmware loops rather than emulator hangs: -The option-firmware ...",""],
["./--firmware-requirements.html","2. Installation &#62; Firmware Requirements","EmulatR requires an SRM console firmware image to execute. The DS10 reference image is an SRM V7.3 build (ds10_v7_3.exe).",""],
["./--first-startup.html","2. Installation &#62; First Startup","The simplest first run is EmulatrLaunch.exe from the installation: it creates a system, gives it a profile directory to run in, and starts the emu...",""],
["./--floating-point-consideration.html","5. Architecture &#38; Internals &#62; 5.1 Execution, Decode &#38; Internals &#62; Floating-Point Considerations","Alpha floating point is wider than a single IEEE implementation, and modeling it faithfully has several moving parts: four data formats, a separat...",""],
["./--ghidra.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; Ghidra","Ghidra is the NSA&#39;s open-source software reverse-engineering (SRE) suite. In EmulatR it is the tool used to read the SRM firmware: once the compre...",""],
["./--glossary--------------------.html","6. Reference &#62; Glossary","Placeholders, terms and acronyms used throughout this guide.",""],
["./--grainfactorylib.html","5. Architecture &#38; Internals &#62; 5.1 Execution, Decode &#38; Internals &#62; grainFactoryLib","A grain is the unit of instruction semantics in V6: each decoded instruction resolves to a single grain leaf that implements its behavior. grainFa...",""],
["./--halt-button-is-in_-boot-not-.html","7. Troubleshooting &#62; Halt Button is IN, BOOT NOT POSSIBLE","Symptom At power-up the console prints \"Halt Button is IN, AUTO_ACTION ignored\", and at the &#62;&#62;&#62; prompt any boot attempt (for ex...",""],
["./--ide-devices.html","4. Operating EmulatR &#62; 4.4 Storage &#62; IDE Devices","On the DS10 / DS20 (Tsunami) the CY82C693 provides the IDE controller, exposed on PCI bus 0, slot 5, function 1 (\"Cypress 82C693 IDE\" in...",""],
["./--iso-9660-pfd-(cd001).html","4. Operating EmulatR &#62; 4.4 Storage &#62; ISO-9660 PVD (CD001)","An ISO-9660 image begins with a 16-block (32 KiB) system area, after which LBA 16 holds the Primary Volume Descriptor (PVD). The firmware&#39;s first ...",""],
["./--launching-emulatr.html","3. Quick Start &#62; Launching EmulatR","Run from your system&#39;s profile directory - the directory the launcher created, which holds firmware\\, config\\, logs\\ and the platform manifest. Th...",""],
["./--list-_-display-_-update.html","4. Operating EmulatR &#62; 4.6 Firmware Update Utility (LFU) &#62; LFU Commands (List / Display / Update)","At the UPD&#62; prompt the utility presents a function menu. ? or Help scrolls it:",""],
["./--loading-firmware.html","3. Quick Start &#62; Loading Firmware","Pass the SRM image explicitly so the path resolves regardless of the ini default:",""],
["./--memory----------------------.html","5. Architecture &#38; Internals &#62; 5.2 Memory, Addressing &#38; Deep Dives &#62; Memory","GuestMemory (memoryLib) is the single physical-memory interface -- a passive byte-store with no opinion about devices or faults. It pages the gues...",""],
["./--memory-map--iprs.html","5. Architecture &#38; Internals &#62; 5.2 Memory, Addressing &#38; Deep Dives &#62; Memory Map &#38; IPRs","This appendix is the register-level companion to the Memory and Addressing pages. It names the two internal-processor-register (IPR) namespaces Em...",""],
["./--overview--------------------.html","5. Architecture &#38; Internals &#62; Overview","EmulatR is a full-system, high-fidelity emulator of the DEC Alpha AXP platform -- specifically the 21264 (EV6) processor and the 21272 (Tsunami / ...",""],
["./--putty-_-plink-_-teraterm-_-m.html","4. Operating EmulatR &#62; 4.2 Console Connectivity &#62; Terminal Clients (PuTTY / Plink / TeraTerm / MobaXterm / Netcat)","Connection steps for the common clients. In every case the target is localhost port 10023 (or a remote host and the port the instance was started ...",""],
["./--reaching-the-srm-prompt.html","3. Quick Start &#62; Reaching the SRM Prompt","After launch the firmware proceeds through power-up to the console. The visible sequence is:",""],
["./--required-tools--frameworks.html","2. Installation &#62; Required Tools &#38; Frameworks","Tooling and libraries used by EmulatR. Versions below are those the project currently builds against.",""],
["./--scsi-devices.html","4. Operating EmulatR &#62; 4.4 Storage &#62; SCSI Devices","SCSI is the working storage path. EmulatR models an NCR 53C810 host adapter (KZPAA lineage), presented at PCI bus 0, slot 8, function 0 with vendo...",""],
["./--sdi-devices-_-dssi-devices-_.html","4. Operating EmulatR &#62; 4.4 Storage &#62; SDI / DSSI / ST506 Devices","These are legacy DEC / PC disk interconnects, included here for reference. None is present on the DS10, which uses the CY82C693 IDE / ATAPI channe...",""],
["./--srm-environment-variables.html","4. Operating EmulatR &#62; 4.3 SRM Console &#62; SRM Environment Variables","The complete, annotated list of SRM console variables (auto_action, the boot_* set, com1_* / com2_*, the d_* diagnostics group, the N1 to N16 NVRA...",""],
["./--srm-overview.html","4. Operating EmulatR &#62; 4.3 SRM Console &#62; SRM Overview","At &#62;&#62;&#62; you interact with the console using show (display a variable), set (change a variable), and device / diagnostic commands. Settings...",""],
["./--srm-performance-logging.html","4. Operating EmulatR &#62; 4.8 Logging &#38; Diagnostics &#62; SRM Performance Logging","Performance-run output depends on which \"performance run\" you mean.",""],
["./--storage-interconnect-and-fab.html","4. Operating EmulatR &#62; 4.4 Storage &#62; Storage Interconnect and Fabric","On the DS10 target the storage path is short and fixed: the EV6 reaches the PCI hose through the Pchip, the Cypress CY82C693 sits on PCI bus 0 (sl...",""],
["./--supported-systems.html","1. Introduction &#62; Supported Systems","EmulatR targets the Tsunami / Typhoon AlphaServer line. The emulated hardware reported by the SRM console (show config) reflects a DS10-class mach...",""],
["./--system-disk-configuration.html","4. Operating EmulatR &#62; 4.4 Storage &#62; System Disk Configuration","This topic takes you end to end: create an EmulatR virtual disk, point the platform manifest at an OpenVMS distribution ISO and at the new disk, b...",""],
["./--tcp-console-overview.html","4. Operating EmulatR &#62; 4.2 Console Connectivity &#62; TCP Console Overview","EmulatR serves the console over a RAW TCP socket -- no Telnet option negotiation. Defaults:",""],
["./--virtual-cdrom.html","4. Operating EmulatR &#62; 4.4 Storage &#62; Virtual CDROM (dqa1)","dqa1 (\"EMULATR VIRTUAL CDROM\") is the virtual optical device the firmware probes for option firmware during power-up. It is the ATAPI un...",""],
["./--virtual-disk-images.html","4. Operating EmulatR &#62; 4.4 Storage &#62; Virtual Disk Images","An emulated fixed disk is backed by a plain raw, flat image file: the byte at offset LBA × sector-size is the first byte of that logical block. Th...",""],
["./--what-is-emulatr.html","1. Introduction &#62; What is EmulatR","EmulatR is a software emulator of the Digital (DEC) Alpha AXP family. It models the 21264 / 21264A (EV6 / EV67) processor and the 21272 \"Tsun...",""],
["./--windows-registry-settings.html","6. Reference &#62; Windows Registry Settings","Every key EmulatR persists is listed here. You should not normally need this topic -- every value below has a control in the launcher UI -- but it...",""],
["./1_-introduction.html","Introduction","EmulatR is a software emulator of the Digital (DEC) Alpha AXP family. It models the 21264 / 21264A (EV6 / EV67) processor and the 21272 \"Tsun...",""],
["./2_-installation.html","Installation","This chapter covers the two ways to get EmulatR onto a machine -- the Windows installer (the route for beta testers) and building from source -- a...",""],
["./3_-quick-start----------------.html","3. Quick Start","The fastest path from a built binary to an interactive SRM prompt, and back down cleanly. Each step has its own topic below; follow them in order.",""],
["./4_-operating-emulatr----------.html","Operating EmulatR","Day-to-day tasks once EmulatR is built and runs: configuring the machine, attaching a console, driving the SRM console, managing storage and snaps...",""],
["./4_1-configuring--running.html","4. Operating EmulatR &#62; 4.1 Configuring &#38; Running","How the emulated machine is configured by its platform manifest, and the ways to launch a run -- a quiet cold boot, a traced boot, a long unattend...",""],
["./4_2-console-connectivity.html","4. Operating EmulatR &#62; 4.2 Console Connectivity","EmulatR serves its console over a RAW TCP socket. This subsection covers what the console is, how the port is chosen, and how to attach each commo...",""],
["./4_3-srm-console.html","4. Operating EmulatR &#62; 4.3 SRM Console","At the &#62;&#62;&#62; prompt the console accepts show and set commands plus device and diagnostic commands; variable changes persist to the flash / ...",""],
["./4_4-storage.html","4. Operating EmulatR &#62; 4.4 Storage","Storage on the DS-class targets is presented through the Cypress CY82C693 south-bridge IDE / ATAPI channels; the ES40 uses the ALi M1543C / M5229 ...",""],
["./4_6-firmware-update-utility-(l.html","4. Operating EmulatR &#62; 4.6 Firmware Update Utility (LFU)","The Loadable Firmware Update (LFU) utility runs during power-up -- after the option-firmware scan finds nothing on CD or floppy, the firmware drop...",""],
["./4_7-guest-boot----------------.html","4. Operating EmulatR &#62; 4.7 Guest Boot","From the SRM console prompt (&#62;&#62;&#62;) you boot a device with boot &#60;device&#62; [-fl root,flags]. The device is a console device name; the o...",""],
["./4_8-logging--diagnostics.html","4. Operating EmulatR &#62; 4.8 Logging &#38; Diagnostics","EmulatR&#39;s diagnostics are driven by runtime EMULATR_* trace gates and a built-in retire profiler. Most output goes to the process&#39;s standard error...",""],
["./5_-architecture--internals----.html","Architecture &#38; Internals","How EmulatR is built and how a cold boot actually runs. These pages are the operator lens; it presents enough detail to reason about the machine w...",""],
["./5_7-scsi.html","5. Architecture &#38; Internals &#62; 5.7 SCSI","SCSI is the bootable storage path. The IDE / ATAPI channel exists so the firmware can enumerate a disk and a CD-ROM; the guest operating system li...",""],
["./5_8-comjit.html","5. Architecture &#38; Internals &#62; 5.8 Cross-Platform JIT Architecture","To support multi-architecture targets like macOS/Intel (x86_64) and macOS/ARM (Apple Silicon) alongside your existing Windows/Linux x64 targets, t...",""],
["./6_-reference------------------.html","Reference","Look-up material: the full environment-variable table, a glossary of Alpha and EmulatR terms, the build and runtime dependencies, and the project&#39;...",""],
["./7_-troubleshooting------------.html","Troubleshooting","What to check when EmulatR will not start, hangs, boots slowly, is missing a device, or refuses a boot. Several of these are expected behaviors of...",""],
["./82077-controller_.html","5. Architecture &#38; Internals &#62; 5.3 Chipset &#38; Devices &#62; 82077 Floppy Controller","EmulatR models a minimal Intel/DEC 82077AA-class floppy disk controller (FDC) at the legacy ISA base 0x3F0. Its purpose is firmware enumeration, n...",""],
["./8_-appendices---developer-refe.html","Appendices - Developer Reference","The deep developer lens: per-platform reference material and register-level engineering notes that sit beneath the operator-facing chapters.",""],
["./8_1-platform-appendices.html","8. Appendices - Developer Reference &#62; 8.1 Platform Appendices","Per-model reference material. The DS10 carries the fullest appendix, with detailed sub-topics, because it was the first platform driven end to end...",""],
["./8_2-subsystem-internals-------.html","5. Architecture &#38; Internals &#62; 5.1 Execution, Decode &#38; Internals","Developer-reference notes on individual subsystems: how floating point is approached, how the grain dispatch machinery is generated from tables, a...",""],
["./8_3-architecture-deep-dives---.html","5. Architecture &#38; Internals &#62; 5.2 Memory, Addressing &#38; Deep Dives","These appendices are the register-and-address-level companions to chapter 5 (Architecture &#38; Internals). Where chapter 5 explains a subsystem f...",""],
["./8_4-tools.html","8. Appendices - Developer Reference &#62; 8.2 Tools","The external tools used to build, profile, reverse-engineer, and document EmulatR. None of these are required to run the emulator; they are the de...",""],
["./9-iteration-baseline.html","9. Performance &#62; 9-Iteration-Baseline","BATCH2 — release build, fixed 3.5B cycles, pinned per leg (20:06–20:44)",""],
["./acceleration-program-status.html","9. Performance &#62; Acceleration Program Status","This topic is the one-page map of the execution-acceleration program: what is implemented, what is designed but not built, what is ruled, and what...",""],
["./ali-m1543c-south-bridge-interf.html","5. Architecture &#38; Internals &#62; 5.3 Chipset &#38; Devices &#62; South Bridge &#62; ALi M1543C South-Bridge Interface","The Acer Labs (ALi) M1543C is the PCI-to-ISA south bridge of the AlphaServer ES40 and ES45 -- the counterpart to the Cypress CY82C693 used by the ...",""],
["./alpha_diasm.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script &#62; alpha_disasm","tools/alpha_disasm.py is a minimal Alpha (EV6) disassembler for inspecting raw firmware and decompressed PAL images. It is deliberately NOT a full...",""],
["./analyze_retire_trace.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script &#62; analyze_retire_trace","Finds the dominant PC loop in a TRACE_RETIRE_COMPACT retire trace. It counts hot PCs and locates the longest consecutive repeating instruction-gro...",""],
["./antivirus-and-cloud-sync.html","6. Reference &#62; Antivirus and Cloud Sync","A running EmulatR system writes continuously to its run directory: disk images of several gigabytes, snapshots, NVRAM, logs and traces. Real-time ...",""],
["./block-execution.html","5. Architecture &#38; Internals &#62; 5.6 Platform Execution Modes &#38; Clock &#62; Block-Execution","Block execution is EmulatR&#39;s normal execution model. Once a run of straight-line code has executed, EmulatR lays its already-decoded instructions ...",""],
["./block-max-internals.html","5. Architecture &#38; Internals &#62; 5.6 Platform Execution Modes &#38; Clock &#62; Block-MAX-Internals","Field Value Audience Architecture / Internals Scope The dial itself, the machinery it governs, and every measured or structural effect it has on r...",""],
["./boot-sequences.html","8. Appendices - Developer Reference &#62; 8.3 Source Cross Reference","Every claim EmulatR makes about the machine is meant to be traceable to something that is not EmulatR. This appendix says where those authorities ...",""],
["./boot-transcripts.html","4. Operating EmulatR &#62; 4.3 SRM Console &#62; Successful Boot to SRM (per platform)","Reference transcripts of a healthy boot to the SRM console prompt for each platform, so the testing teams have a known-good baseline to diff their...",""],
["./boot.html","4. Operating EmulatR &#62; 4.3 SRM Console &#62; boot","On real SRM, boot bootstraps the operating system using bootdef_dev and boot_osflags. On EmulatR the bootstrap runs: OpenVMS Alpha V8.3 boots from...",""],
["./booting-from-an-iso-image.html","8. Appendices - Developer Reference &#62; 8.1 Platform Appendices &#62; Booting/Configure A New OpenVMS Instance from an ISO","Step 1. Boot from a configured DQA1 OpenVMS Operating System ISO image.",""],
["./bring-up-probes.html","4. Operating EmulatR &#62; 4.8 Logging &#38; Diagnostics &#62; Bring-Up Probes (EMULATR_BRINGUP_PROBES)","Over hardware bring-up, many one-off probe prints were left in the run path -- per-step CPU samplers, memory watchpoints, PAL-transition traces, a...",""],
["./build_test_run2.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script &#62; build_test_run","Rebuilds the project (RelWithDebInfo), runs the chipset halt-register doctest, then hands off to launch_vms_boot.sh. Deployed to &#60;run-dir&#62;/t...",""],
["./chipset.html","5. Architecture &#38; Internals &#62; 5.3 Chipset &#38; Devices","In EmulatR the chipset is the adapter between the CPU(s) and the devices whose accesses it routes. Every CPU load, store, and fetch enters the chi...",""],
["./choosing-the-host-adapter.html","4. Operating EmulatR &#62; 4.9 Networking (EWA0) &#62; Choosing the Host Adapter (Wi-Fi and Wired)","EmulatR bridges the emulated DE500-BA (EWA0) onto one of the host&#39;s own network adapters. Which adapter you choose decides whether networking work...",""],
["./clock-frequency-mhz.html","5. Architecture &#38; Internals &#62; 5.6 Platform Execution Modes &#38; Clock &#62; Clock Frequency and the MHz Reading","The SRM banner and show config report a CPU speed -- on the DS10 profile, 268 MHz. That number is not a hardcoded banner string and it is not read...",""],
["./command-line-options.html","4. Operating EmulatR &#62; 4.1 Configuring &#38; Running &#62; Command Line Options","The launch scripts (tools/run_&#60;model&#62;.sh) pass these command-line options (qualifiers) through to the emulator -- supply them after a bare -...",""],
["./cy82c693-.html","5. Architecture &#38; Internals &#62; 5.3 Chipset &#38; Devices &#62; South Bridge &#62; Cypress &#62; CY82C693","The Cypress CY82C693 is the combination PCI-to-ISA bridge / IDE controller / Super I/O used as the south bridge on the DS10 and DS20 (PC264 lineag...",""],
["./cypress.html","5. Architecture &#38; Internals &#62; 5.3 Chipset &#38; Devices &#62; South Bridge &#62; Cypress","Cypress Semiconductor (PCI vendor ID 0x1080) is the maker of the CY82C693 \"HyperCore\" combination PCI-to-ISA bridge used as the south br...",""],
["./de500-ethernet-21143.html","5. Architecture &#38; Internals &#62; 5.3 Chipset &#38; Devices &#62; DE500 Ethernet (21143 Tulip)","EmulatR models a DEC DE500-class Fast Ethernet adapter built on the DECchip 21143 (\"Tulip\") PCI Ethernet MAC.",""],
["./decchip-21274-(titan).html","5. Architecture &#38; Internals &#62; 5.3 Chipset &#38; Devices &#62; DECchip 21274 (Titan)","Titan is the DECchip 21274 core-logic chipset -- the memory controller and PCI/AGP host bridge for the 21264A/21264B (EV67/EV68) machines: the DS1...",""],
["./decompile_ds10.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script &#62; decompile_ds10","Dumps C source from an already-analyzed Ghidra project. This script only runs the decompile post-script against the saved program -- it does not i...",""],
["./decompressor-internals.html","5. Architecture &#38; Internals &#62; 5.4 Firmware Decode &#38; Decompression &#62; Decompressor Internals","This appendix is the source-level companion to the Firmware Decode &#38; Decompression page. It identifies the DEC sources behind the cold-boot se...",""],
["./diagnostic-instrumentation.html","5. Architecture &#38; Internals &#62; 5.6 Platform Execution Modes &#38; Clock &#62; Model Badging (IIC Discriminator)","The SRM firmware brands each machine with a platform name in its power-up banner (\"AlphaServer DS20\", \"AlphaPC 264DP\", and so ...",""],
["./diag_halt_irq4.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script &#62; diag_halt_irq4","2026-06-14 runbook that disambiguates the IRQ4 / halt gate: World A (a clr_irq* write clears a real interrupt source) versus World C (the code is ...",""],
["./emulatr-subsystems.html","4. Operating EmulatR &#62; 4.8 Logging &#38; Diagnostics &#62; Logging Subsystems","EmulatR routes its diagnostic output through a small set of named subsystems. Each is the &#60;subsys&#62; argument accepted by the logging command-...",""],
["./examples---json.html","5. Architecture &#38; Internals &#62; 5.6 Platform Execution Modes &#38; Clock &#62; &#60;firmware&#62;_warp.json -- Calibrated-Delay Census","&#60;firmware&#62;_warp.json is the calibrated-delay census: a run product, stem-keyed beside the firmware image it was measured against. It records...",""],
["./execution-matrix.html","6. Reference &#62; Execution Matrix (Models x Modes)","A quick reference for the testing teams: each supported model crossed with its two execution modes -- Virtual (ISP) and REAL_HW (Silicon) -- and w...",""],
["./execution-modes.html","5. Architecture &#38; Internals &#62; 5.6 Platform Execution Modes &#38; Clock","The Alpha console firmware runs in one of two modes, and the choice changes its entire initialization strategy. Virtual mode (ISP) is DEC&#39;s pre-si...",""],
["./execution-pipeline.html","5. Architecture &#38; Internals &#62; 5.2 Memory, Addressing &#38; Deep Dives &#62; Execution Pipeline","EmulatR executes guest Alpha instructions through two cooperating paths: a six-stage main pipeline that models the full instruction lifecycle, and...",""],
["./firmware-images-exe-and-rom.html","2. Installation &#62; Firmware Requirements &#62; Firmware Images: .exe and .rom","Two files in the firmware\\ directory can share a name and differ only by extension - ds20_v7_3.exe and ds20_v7_3.rom - and they are not two copies...",""],
["./goals--objectives.html","1. Introduction &#62; Goals &#38; Objectives","EmulatR is a full-system, cycle-based, high-fidelity emulator of the DEC Alpha AXP architecture. Its purpose is not to approximate an Alpha but to...",""],
["./help--manual.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; Help &#38; Manual","Help &#38; Manual (EC Software) is the documentation authoring tool that produces this help project. Every page you are reading is a Help &#38; Ma...",""],
["./host-decompressor.html","5. Architecture &#38; Internals &#62; 5.4 Firmware Decode &#38; Decompression &#62; Host Decompressor","tools/host_decompressor is a native, host-compiled build of the original DEC SRM Huffman / inflate decompressor. It serves as a trusted reference ...",""],
["./hwrpb---ds20.html","5. Architecture &#38; Internals &#62; 5.5 PALcode, HWRPB &#38; SMP &#62; HWRPB Key/Value Offset Map","This page documents the kKeyValue offset map for the HWRPB (Hardware Restart Parameter Block) and its chained structures, as encoded in deviceLib/...",""],
["./installation-test-plan.html","2. Installation &#62; Installation Test Plan","Kit      : EmulatR ____________   (copy it from the console banner)",""],
["./installing-with-the-windows-installer.html","2. Installation &#62; Installing with the Windows Installer","Beta and release builds of EmulatR are distributed as a single Windows setup program (EmulatR_V&#60;version&#62;-setup.exe). The installer places a ...",""],
["./known-gaps.html","1. Introduction &#62; Known Gaps","Release checkpoint = DS10 + DS20 + ES40 certified to the same boot milestone. All three reach P00&#62;&#62;&#62;, and that three-platform console gat...",""],
["./launch_vms_boot.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script &#62; launch_vms_boot","Cold-boots EmulatR (DS10/EV6) and boots OpenVMS Alpha V8.2 from dqa1. Deployed to &#60;run-dir&#62;/tools/ by CMake POST_BUILD; lives in tools/ but ...",""],
["./license.html","1. Introduction &#62; License","ASA-EMulatR Copyright &#169; 2025–2026 Timothy Peer (eNVy Systems, Inc.) https://envysys.com     eNVy Systems Non-Commercial License v1.1 &#38;nb...",""],
["./mkdisk.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script &#62; mkdisk","Raw disk-image generator for the emulated ATA fixed disk (the dqa install target). It creates a blank, writable, raw flat disk image with 512-byte...",""],
["./naming-the-host-adapter.html","4. Operating EmulatR &#62; 4.9 Networking (EWA0) &#62; Naming the Host Adapter (EMULATR_NET_ADAPTER)","By default EmulatR chooses the host adapter for EWA0 by itself. This page covers everything needed to name one explicitly instead, using EMULATR_N...",""],
["./networking-ewa0.html","4. Operating EmulatR &#62; 4.9 Networking (EWA0)","4.9 Networking (EWA0) EmulatR can bridge the emulated DE500-BA Ethernet controller to a real host network adapter, so the guest becomes an ordinar...",""],
["./palcode-platform-bases.html","5. Architecture &#38; Internals &#62; 5.5 PALcode, HWRPB &#38; SMP","PAL$CPU0_START_BASE %x100  PAL$CPU1_START_BASE %x108  PAL$PRIMARY %x200   PAL$CALLBACK %x210   PAL$HALT_SWITCH_IN %x220  ...",""],
["./per-cpu-halt-codes.html","6. Reference &#62; Per-CPU Halt Codes","When an Alpha processor stops and drops into console I/O mode, PALcode records WHY in the processor&#39;s per-CPU slot of the HWRPB. A developer readi...",""],
["./performance-warp.html","9. Performance &#62; Warp","Firmware waits for hardware by spinning: during probes and resets the SRM busy-waits on the cycle counter (RSCC) for a fixed interval. Executed in...",""],
["./performance.html","9. Performance","This chapter covers EmulatR&#39;s execution-performance architecture: the staged interpretive pipeline that anchors correctness, the acceleration prog...",""],
["./phase1-dispatch-gate.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script &#62; phase1 dispatch gate","AlphaCpuAgent Phase-1 acceptance gate. It proves that the dispatcher-driven boot (EMULATR_DISPATCH=1, one AlphaCpuAgent under SequentialDriver cal...",""],
["./pipeline-execution-(internals).html","8. Appendices - Developer Reference &#62; 8.1 Platform Appendices &#62; Pipeline Execution (Internals)","This topic maps the pipeline machinery -- from instruction decode through block execution to interrupt delivery -- as a Bachman diagram. Boxes are...",""],
["./platform-execution-mode-isp-(e.html","5. Architecture &#38; Internals &#62; 5.6 Platform Execution Modes &#38; Clock &#62; Platform Execution Mode: ISP vs Silicon","1. Why this matters (the significance) EmulatR presents the Alpha console firmware with a single, firmware-visible flag that tells it whether it i...",""],
["./platform-execution.html","5. Architecture &#38; Internals &#62; 5.6 Platform Execution Modes &#38; Clock &#62; Platform Execution","Every supported model is launched the same way, through one script. The model is not really a flag you choose -- it follows the firmware image the...",""],
["./platform-identity-and-geometry.html","4. Operating EmulatR &#62; 4.1 Configuring &#38; Running &#62; Platform Identity &#38; Memory Geometry","Two rules settle what machine EmulatR is about to be, and both run at argument resolution -- before the machine is constructed. The firmware image...",""],
["./platform-memory-reference.html","8. Appendices - Developer Reference &#62; 8.1 Platform Appendices &#62; Platform Memory Reference","This appendix records the vendor memory specifications for the AlphaServer models EmulatR models or plans to model: how much memory each chassis p...",""],
["./platformeditor-web-ui.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; Platform Editor","The Platform Editor is a desktop application for authoring and validating an EmulatR platform device manifest -- the &#60;firmware&#62;_platform.jso...",""],
["./post-flash.html","5. Architecture &#38; Internals &#62; 5.4 Firmware Decode &#38; Decompression &#62; Post Flash","Source Function Source Location platform_init1()                      kernel.c:1287   ...",""],
["./profile_resolve.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script &#62; profile_resolve","Annotates RetireProfiler dumps with SRM and PAL symbols. It reads one or more RetireProfiler dump files, labels each bucket with the best-known SR...",""],
["./qt-creator.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; Qt Creator","Qt Creator is the IDE used to develop and build EmulatR. It drives the CMake build, manages the compiler kit, and provides the editor and debugger...",""],
["./release-notes.html","Release Notes","EmulatR brings the real DEC/Compaq/HP Alpha SRM console firmware to life on emulated Tsunami/Typhoon-class hardware. This chapter records what eac...",""],
["./releasenotesv1_6-.html","Release Notes &#62; V1.6 (Beta)","EmulatR brings the real DEC/Compaq/HP Alpha SRM console firmware to life on emulated Tsunami/Typhoon-class hardware. Each release records what lan...",""],
["./releasenotesv2_0-.html","Release Notes &#62; T2.0-16 (Beta)","The full User and Developer Reference is published online at https://emulatrapp.github.io/EmulatR-docs/. It is the same guide the kit installs as...",""],
["./reset-into-secondary-boot.html","5. Architecture &#38; Internals &#62; 5.6 Platform Execution Modes &#38; Clock &#62; Reset into Secondary Boot (CSERVE START Handoff)","This topic documents the execution mode EmulatR enters when the SRM console hands control to a secondary bootstrap -- the guest operating-system l...",""],
["./run-directory-contents.html","3. Quick Start &#62; Running from a Run Directory &#62; Run-Directory Contents","An inventory of the run directory, out/build/&#60;tree&#62;-&#60;config&#62;/run/ - for example out/build/v6-relwithdebinfo/run/. This directory is th...",""],
["./running-from-a-run-directory.html","3. Quick Start &#62; Running from a Run Directory","The run directory is the folder that holds the built executable -- out/build/&#60;tree&#62;-&#60;config&#62;/run/, where &#60;tree&#62; is the release t...",""],
["./running-from-the-shell.html","3. Quick Start &#62; Running from the Shell","EmulatR is a console application driven from a command line. The standard execution shell is bash -- the project&#39;s own launch and trace scripts ar...",""],
["./run_fw_sh.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script &#62; run_fw.sh","Launches EmulatR V6 against one v7_3 firmware image with 4 GiB of RAM. Resolves the model variant, sets the [System] model line in config/Emulatr....",""],
["./script.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script","The tools topic-hive documents the developer and operator scripts that live in the EmulatR V4 source tools/ directory. The shell scripts are deplo...",""],
["./scsi-bus-control-lines.html","5. Architecture &#38; Internals &#62; 5.7 SCSI &#62; SCSI Bus Control Lines","The SCSI parallel bus carries data lines plus nine control signals, physically shared by every device on the cable:",""],
["./set.html","4. Operating EmulatR &#62; 4.3 SRM Console &#62; set","set changes a console variable and persists it to the flash / NVRAM image; show reads it back. Example session:",""],
["./show-config.html","4. Operating EmulatR &#62; 4.3 SRM Console &#62; show config","show config prints the full configuration table: the SRM and PALcode versions; the processor (Alpha EV6 pass 1, 268 MHz); core logic (Cchip 21272-...",""],
["./show-device.html","4. Operating EmulatR &#62; 4.3 SRM Console &#62; show device","show device lists enumerated devices. The transcript below is a DS10 run; a DS20 - the shipped default model - also lists its SCSI system disk dka0:",""],
["./show-memory.html","4. Operating EmulatR &#62; 4.3 SRM Console &#62; show memory","The memory array is reported in the configuration table:",""],
["./smp-(multiprocessor)-design.html","5. Architecture &#38; Internals &#62; 5.5 PALcode, HWRPB &#38; SMP &#62; SMP (MultiProcessor) Design","================================================================================",""],
["./snapmap.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script &#62; snapmap","Region mapper for EmulatR .axpsnap snapshot files, producing a 010-Editor-style hex map. It decodes the snapshot header, the chipset block, and th...",""],
["./software-verify.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; Software Verify","Software Verify (Software Verify Limited) makes a family of C/C++ analysis tools for Windows; the one used in EmulatR development is Performance V...",""],
["./southbridge.html","5. Architecture &#38; Internals &#62; 5.3 Chipset &#38; Devices &#62; South Bridge","The south bridge is the PCI-to-ISA bridge that carries the legacy I/O plane of an Alpha system: the 8259A interrupt-controller pair, the 8254 time...",""],
["./srm-boot-call-stack.html","8. Appendices - Developer Reference &#62; 8.1 Platform Appendices &#62; SRM Boot Call-Stack","This appendix names the ordered path from power-up to the &#62;&#62;&#62; prompt, and where each stage lives. Its practical use is localization: when...",""],
["./srm-boot-_-srm-commands-prompt.html","8. Appendices - Developer Reference &#62; 8.1 Platform Appendices &#62; Appendix - DS10 &#62; SRM Boot, Commands &#38; SuperIO","The DS10 firmware reference. SRM boot and the &#62;&#62;&#62; command set are covered operationally in the Quick Start and Operating EmulatR chapters...",""],
["./task-matrix-_-timeout-loops.html","8. Appendices - Developer Reference &#62; 8.1 Platform Appendices &#62; Appendix - DS10 &#62; Task Matrix &#38; TimeOut Loops","Two pieces of DS10 engineering reference: the concrete bounds of the firmware&#39;s device-wait loops (useful when judging whether a long pause is a h...",""],
["./terms-of-use.html","1. Introduction &#62; Terms of Use","IMPORTANT -- PLEASE READ BEFORE INSTALLING OR USING EMULATR.",""],
["./testing-supported-cest-cases.html","8. Appendices - Developer Reference &#62; Testing (draft) &#62; Supported Test Cases","$ Emulatr_tests.exe --list-test-cases  [doctest] listing all test case names ================================================================...",""],
["./testing.html","8. Appendices - Developer Reference &#62; Testing (draft)","EmulatR is validated two ways: a doctest unit-test suite, and a boot-gate that a build must still pass at the console level. The determinism of th...",""],
["./time-of-year-clock-toy.html","5. Architecture &#38; Internals &#62; 5.6 Platform Execution Modes &#38; Clock &#62; Time-of-Year Clock (TOY)","The Time-of-Year clock is the machine&#39;s battery-backed real-time clock: an MC146818-compatible part in the Cypress CY82C693 southbridge, reached t...",""],
["./tools-script-reference.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; Tools Script Reference","A consolidated inventory of every shell (*.sh) and Python (*.py) script in the EmulatR source tools/ directory. This is the reader-facing companio...",""],
["./trace_halt.html","8. Appendices - Developer Reference &#62; 8.2 Tools &#62; script &#62; trace_halt","Console-armed retire trace plus a TIG bring-up canary. Deployed to &#60;run-dir&#62;/tools/ by CMake POST_BUILD. It cold-boots to the &#62;&#62;&#62; p...",""],
["./tsunami-error-chain.html","5. Architecture &#38; Internals &#62; 5.3 Chipset &#38; Devices &#62; Tsunami Error Chain (PERROR / No Devsel)","EmulatR models the 21272 Pchip PCI error-reporting chain end to end (21272 HRM Ch 8.8 and 10.2.5.6-10.2.5.8). When a PCI transaction fails in a wa...",""],
["./tsunami-_-typhoon.html","5. Architecture &#38; Internals &#62; 5.3 Chipset &#38; Devices &#62; Tsunami \\ Typhoon","Tsunami is the DEC/Compaq/HP 21272 core-logic chipset for 21264 (EV6) systems -- the memory controller and PCI host bridge for the DS10, DS20, and...",""],
["./version-administration.html","1. Introduction &#62; EmulatR Version Numbering and Release Stages","EmulatR uses a single version identity across the console badge, the documentation, and the distribution kit. The format follows the Digital (DEC)...",""],
["./virtual-floppy-(dva0).html","4. Operating EmulatR &#62; 4.4 Storage &#62; Virtual Floppy (dva0)","dva0 (\"EMULATR VIRTUAL FLOPPY\") is not implemented.",""],
["./virtualization-methods.html","5. Architecture &#38; Internals &#62; 5.6 Platform Execution Modes &#38; Clock &#62; Virtualization Methods","EmulatR can present the firmware with one of two execution-path identities. The choice is made by a single firmware routine -- the SRM console&#39;s p...",""],
["./warp-variants-and-cycle-accoun.html","5. Architecture &#38; Internals &#62; 5.6 Platform Execution Modes &#38; Clock &#62; WARP Variants and Cycle-Accounting","WARP collapses idle and delay spins by fast-forwarding the simulation clock to a known target instead of executing every cycle. This topic catalog...",""],
["./windows-defender-firewall.html","6. Reference &#62; Windows Defender Firewall","Select button:  Allow Access.  Disable Antivirus for the directory tree which contains the EmulatR storage .vDisk, vTable, and .img files.",""]];
